[profile.default]
src = "src"
out = "out"
libs = ["lib"]


version = "0.8.26" 
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
  "@1inch/limit-order-protocol/=lib/limit-order-protocol/contracts/",
  "@1inch/solidity-utils/=lib/solidity-utils/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
  "solidity-bytes-utils/=lib/solidity-bytes-utils/"
]


# Base Network Configuration
[rpc_endpoints]
localchain = "${LOCALCHAIN_URL}"
basechain = "${BASE_URL}"
base-sepolia = "${BASE_URL}"
etherum = "${ETHERUM_URL}"
sonicchain = "${SONIC_URL}"
hedera = "${HEDERA_URL}"
avalanche = "${AVALANCHE_URL}"
anvillocal = "${ANVIL_URL}"


[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
