[profile.default]
src = "src"
out = "out"
libs = ["lib"]


version = "0.8.26" 

remappings = ["@limit-order-protocol/=contracts/lib/limit-order-protocol/"]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
